// Mundo_2/z_missoes_praticas/nivel3/livros-next/src/classes/modelo/Editora.tsx
import React, { useState } from "react";

class Editora extends React.Component<EditoraProps> {
  constructor(props: EditoraProps) {
    super(props);
  }
  render() {
    let {codEditora, nome} = this.props;
    return (
      <>
        <div>
          <h1>Editora</h1>
          <p>Código: {/*this.props.*/codEditora}</p>
          <p>Nome: {/*this.props.*/nome}</p>
        </div>
      </>
    );
  }
}

export interface EditoraProps {
  codEditora: number;
  nome: string;
}

export default Editora;

// Mundo_2/Angular/pratica/livros-angular/src/app/editora.ts
import { Component, Input } from '@angular/core';

export interface EditoraProps {
  codEditora: number;
  nome: string;
}

@Component({
  selector: 'app-editora',
  template: `
    <div>
      <h1>Editora</h1>
      <p>Código: {{ codEditora }}</p>
      <p>Nome: {{ nome }}</p>
    </div>
  `,
})
export class EditoraComponent {
    codEditora: number = 0;
    nome: string = '';
}
