// Mundo_2/z_missoes_praticas/nivel3/livros-next/src/classes/modelo/Livro.tsx
import React, {useState} from "react";


export interface LivroProps{
    codigo: number;
    codEditora: number;
    titulo: string;
    resumo: string;
    autores: string[];
}

class Livro extends React.Component<LivroProps> {
    constructor(props: LivroProps){
        super(props);
    }
    render(){
        let {codigo, codEditora, titulo, resumo, autores} = this.props;
        return(
            <>
                <div>
                    <h1>Livro</h1>
                    <p>codigo: {codigo}</p>
                    <p>Código da editora: {codEditora}</p>
                    <p>Titulo: {titulo}</p>
                    <p>Resumo: {resumo}</p>
                    <p>Autores: {autores}</p>
                </div>
            </>
        )
    }
}

export default Livro

// Mundo_2/Angular/pratica/livros-angular/src/app/livro.ts
import { Component, Input } from '@angular/core';

export interface LivroProps {
  codigo: number;
  codEditora: number;
  titulo: string;
  resumo: string;
  autores: string[];
}

@Component({
  selector: 'app-livro',
  template: `
    <div>
      <h1>Livro</h1>
      <p>codigo: {{ codigo }}</p>
      <p>Código da editora: {{ codEditora }}</p>
      <p>Titulo: {{ titulo }}</p>
      <p>Resumo: {{ resumo }}</p>
      <p>Autores: {{ autores.join(', ') }}</p>
    </div>
  `,
})
export class LivroComponent {
  codigo: number = 0;
  codEditora: number = 0;
  titulo: string = '';
  resumo: string = '';
  autores: string[] = [];
}
